Admin/Controllers/Select2Controller.cs
using Admin.Entities.SIM;
using Admin.Helper;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Admin.Controllers
{
    public class Select2Controller : Controller
    {
        #region ===== J A S A

        [HttpPost]
        public string Jasa_Jasa_GroupJasa(int pagesize, int pageindex, string filter)
        {
            try
            {
                using (var s = new SIMEntities())
                {
                    var proses = s.ADM_ListGroupJasa.AsQueryable();
                    if (!string.IsNullOrEmpty(filter))
                    {
                        proses = proses.Where(x =>
                            x.GroupJasaName.Contains(filter) ||
                            x.KelompokPerawatan.Contains(filter)
                        );
                    }
                    var totalcount = proses.Count();
                    var models = proses.OrderBy(x => x.GroupJasaName).Skip(pageindex * pagesize).Take(pagesize).ToList();
                    var r = models.ConvertAll(m => new
                    {
                        Id = m.GroupJasaID,
                        Nama = m.GroupJasaName
                    });
                    return JsonConvert.SerializeObject(new
                    {
                        IsSuccess = true,
                        Data = r,
                        TotalCount = totalcount,
                        PageIndex = pageindex,
                    });
                }
            }
            catch (SqlException ex) { return HConvert.Error(ex); }
            catch (Exception ex) { return HConvert.Error(ex); }

        }

        [HttpPost]
        public string Jasa_Jasa_KategoriJasa(int pagesize, int pageindex, string filter, byte? groupjasa)
        {
            try
            {
                using (var s = new SIMEntities())
                {
                    var proses = s.ADM_GetKategoriJasa.AsQueryable();
                    if (groupjasa != null) proses = proses.Where(x => x.GroupJasa == groupjasa);
                    if (!string.IsNullOrEmpty(filter))
                    {
                        proses = proses.Where(x =>
                            x.KategoriJasaID.Contains(filter) ||
                            x.NamaInternational.Contains(filter) ||
                            x.KategoriJasaName.Contains(filter)
                        );
                    }
                    var totalcount = proses.Count();
                    var models = proses.OrderBy(x => x.GroupJasaName).Skip(pageindex * pagesize).Take(pagesize).ToList();
                    var r = models.ConvertAll(m => new
                    {
                        Id = m.KategoriJasaID,
                        Nama = m.KategoriJasaName
                    });
                    return JsonConvert.SerializeObject(new
                    {
                        IsSuccess = true,
                        Data = r,
                        TotalCount = totalcount,
                        PageIndex = pageindex,
                    });
                }
            }
            catch (SqlException ex) { return HConvert.Error(ex); }
            catch (Exception ex) { return HConvert.Error(ex); }

        }

        [HttpPost]
        public string Jasa_Jasa_Dokter(int pagesize, int pageindex, string filter)
        {
            try
            {
                using (var s = new SIMEntities())
                {
                    var proses = s.ADM_ListVendor.AsQueryable();
                    if (!string.IsNullOrEmpty(filter))
                    {
                        proses = proses.Where(x =>
                            x.Kode_Supplier.Contains(filter) ||
                            x.Nama_Supplier.Contains(filter)
                        );
                    }
                    var totalcount = proses.Count();
                    var models = proses.OrderBy(x => x.Kode_Supplier).Skip(pageindex * pagesize).Take(pagesize).ToList();
                    var r = models.ConvertAll(m => new
                    {
                        Id = m.Kode_Supplier,
                        Kode = m.Kode_Supplier,
                        Nama = m.Nama_Supplier
                    });
                    return JsonConvert.SerializeObject(new
                    {
                        IsSuccess = true,
                        Data = r,
                        TotalCount = totalcount,
                        PageIndex = pageindex,
                    });
                }
            }
            catch (SqlException ex) { return HConvert.Error(ex); }
            catch (Exception ex) { return HConvert.Error(ex); }
        }

        [HttpPost]
        public string Jasa_Jasa_Akun(int pagesize, int pageindex, string filter)
        {
            try
            {
                using (var s = new SIMEntities())
                {
                    var proses = s.ADM_GetKomponenAkun.AsQueryable();
                    if (!string.IsNullOrEmpty(filter))
                    {
                        proses = proses.Where(x =>
                            x.Akun_No.Contains(filter) ||
                            x.Akun_Name.Contains(filter)
                        );
                    }
                    var totalcount = proses.Count();
                    var models = proses.OrderBy(x => x.Akun_No).Skip(pageindex * pagesize).Take(pagesize).ToList();
                    var r = models.ConvertAll(m => new
                    {
                        Id = m.Akun_No,
                        Kode = m.Akun_No,
                        Nama = m.Akun_Name
                    });
                    return JsonConvert.SerializeObject(new
                    {
                        IsSuccess = true,
                        Data = r,
                        TotalCount = totalcount,
                        PageIndex = pageindex,
                    });
                }
            }
            catch (SqlException ex) { return HConvert.Error(ex); }
            catch (Exception ex) { return HConvert.Error(ex); }
        }

        [HttpPost]
        public string Jasa_Jasa_Section(int pagesize, int pageindex, string filter)
        {
            try
            {
                using (var s = new SIMEntities())
                {
                    var proses = s.ADM_GetLookUpDetailSection.AsQueryable();
                    if (!string.IsNullOrEmpty(filter))
                    {
                        proses = proses.Where(x =>
                            x.SectionName.Contains(filter) ||
                            x.ID.Contains(filter)
                        );
                    }
                    var totalcount = proses.Count();
                    var models = proses.OrderBy(x => x.SectionName).Skip(pageindex * pagesize).Take(pagesize).ToList();
                    var r = models.ConvertAll(m => new
                    {
                        Id = m.ID,
                        Nama = m.SectionName
                    });
                    return JsonConvert.SerializeObject(new
                    {
                        IsSuccess = true,
                        Data = r,
                        TotalCount = totalcount,
                        PageIndex = pageindex,
                    });
                }
            }
            catch (SqlException ex) { return HConvert.Error(ex); }
            catch (Exception ex) { return HConvert.Error(ex); }
        }

        [HttpPost]
        public string Jasa_Jasa_DataLAB(int pagesize, int pageindex, string filter)
        {
            try
            {
                using (var s = new SIMEntities())
                {
                    var proses = s.ADM_GetLookUpDetailDataLAB.AsQueryable();
                    if (!string.IsNullOrEmpty(filter))
                    {
                        proses = proses.Where(x =>
                            x.ID.Contains(filter) ||
                            x.NamaTest.Contains(filter)
                        );
                    }
                    var totalcount = proses.Count();
                    var models = proses.OrderBy(x => x.NamaTest).Skip(pageindex * pagesize).Take(pagesize).ToList();
                    var r = models.ConvertAll(m => new
                    {
                        Id = m.ID,
                        Nama = m.NamaTest
                    });
                    return JsonConvert.SerializeObject(new
                    {
                        IsSuccess = true,
                        Data = r,
                        TotalCount = totalcount,
                        PageIndex = pageindex,
                    });
                }
            }
            catch (SqlException ex) { return HConvert.Error(ex); }
            catch (Exception ex) { return HConvert.Error(ex); }
        }

        [HttpPost]
        public string Vendor_Vendor_Supplier(int pagesize, int pageindex, string filter)
        {
            try
            {
                using (var s = new SIMEntities())
                {
                    var proses = s.ADM_GetKategoriVendor.AsQueryable();
                    if (!string.IsNullOrEmpty(filter))
                    {
                        proses = proses.Where(x =>
                            x.Kode_Kategori.Contains(filter) ||
                            x.Kategori_Name.Contains(filter)
                        );
                    }
                    var totalcount = proses.Count();
                    var models = proses.OrderBy(x => x.Kode_Kategori).Skip(pageindex * pagesize).Take(pagesize).ToList();
                    var r = models.ConvertAll(m => new
                    {
                        Id = m.Kode_Kategori,
                        Kode = m.Kode_Kategori,
                        Nama = m.Kategori_Name
                    });

Admin/Views/OtherKamar/Index.cshtml
@{
    ViewBag.Title = "Kamar";
    ViewBag.breadcrumb = new List<SelectListItem>()
    {
        new SelectListItem(){ Text = ViewBag.Title, Value = "active" }
    };
}

<form id="formtable">
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title"></h5>
            <div class="heading-elements">
                <ul class="icons-list">
                    <li><a class="panel-action action-plus" href="javascript:isetup.opensetup('CREATE')"></a></li>
                    <li><a class="panel-action action-reload" href="javascript:itable.refresh()"></a></li>
                </ul>
            </div>
        </div>
        <div class="dataTables_wrapper no-footer" style="display: block;">
            <div class="datatable-header" style="padding-bottom: 20px;">
                <div class="form-inline">
                    <div class="form-group">
                        <label>Filter</label>
                        <input type="search" onchange="itable.pageindex=0" data-itable-filter="All" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>Show</label>
                        <select class="form-control itable-pagesize" onchange="itable.refresh()" style="width: auto;">
                            <option selected>10</option>
                            <option>25</option>
                            <option>50</option>
                            <option>100</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="datatable-scroll">
                <table class="table datatable-basic dataTable no-footer table-xxs table-striped">
                    <thead>
                        <tr>
                            <th class="sorting text-center" data-itable-sorting="NoKamar" style="width:150px;">No Kamar<i></i></th>
                            <th class="sorting" data-itable-sorting="NamaKamar">Nama Kamar<i></i></th>
                            <th class="sorting" data-itable-sorting="Section_SectionName">Sal<i></i></th>
                            <th class="sorting text-center" data-itable-sorting="JmlBed">Jml Bed<i></i></th>
                            <th class="sorting text-center" data-itable-sorting="NoLantai">No Lantai<i></i></th>
                            <th class="sorting text-center" data-itable-sorting="Tambahan">Tambahan<i></i></th>
                            <th class="sorting text-center" data-itable-sorting="Kelas_NamaKelas">Kelas<i></i></th>
                            <th class="text-center sorting_disabled" style="width: 100px;">Actions</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
            <div class="datatable-footer">
                <div class="dataTables_info itable-info"></div>
                <div class="dataTables_paginate paging_simple_numbers itable-pagination"></div>
            </div>
        </div>
    </div>
</form>

<script>
    var itable;
    document.addEventListener("DOMContentLoaded", function (event) {
        itable = new iTable({
            url: '@Url.Action("List")',
            table: document.getElementById('formtable'),
            orderby: 'NoKamar',
            tablesuccess: function (r, t) {
                if (r.IsSuccess) {
                    var tbody = '';
                    if (r.Data.length === 0)
                        tbody += `<tr><td colspan="${$(itable.table).find('thead th').length}" class="text-center">----- <b>Tidak ada data</b> -----</td></tr>`;
                    $.each(r.Data, function (index, value) {
                        tbody += '<tr class="odd">';

                        // column
                        tbody += `<td class="text-center">${value.Id}</td>`;
                        tbody += `<td>${value.NamaKamar}</td>`;
                        tbody += `<td>${value.Sal}</td>`;
                        tbody += `<td class="text-center">${value.JmlBed}</td>`;
                        tbody += `<td class="text-center">${value.NoLantai}</td>`;
                        tbody += `<td class="text-center"><input type="checkbox" disabled ${value.Tambahan && 'checked'}/></td>`;
                        tbody += `<td class="text-center">${value.Kelas}</td>`;

                        tbody += '<td class="text-center">';
                        tbody += '<ul class="icons-list">';
                        tbody += '<li class="dropdown">';
                        tbody += '<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-menu9"></i></a>';
                        tbody += '<ul class="dropdown-menu dropdown-menu-right">';

                        // action
                        tbody += '<li><a href="javascript:isetup.opensetup(\'VIEW\',{ id : \'' + value.Id + '\'})"><i class="icon-eye"></i> View</a></li>';
                        tbody += '<li><a href="javascript:isetup.opensetup(\'EDIT\',{ id : \'' + value.Id + '\'})"><i class="icon-pencil"></i> Edit</a></li>';
                        tbody += '<li><a href="javascript:isetup.opensetup(\'DELETE\',{ id : \'' + value.Id + '\'})"><i class="icon-trash"></i> Delete</a></li>';

                        tbody += '</ul>';
                        tbody += '</li>';
                        tbody += '</ul>';
                        tbody += '</td>';
                        tbody += '</tr>';
                    });
                    $(t.table).find('tbody').html(tbody);
                    var footer = generatefootertable(r.TotalCount, t.pagesize, t.pageindex, 'tableordergetdatas');
                    $(t.table).find('.itable-info').html(footer.datainfo);
                    $(t.table).find('.itable-pagination').html(footer.pagination);
                } else {
                    alert(r.Message);
                }
            }
        });
        itable.refresh();
    });
</script>
@Html.Partial("Setup")

Admin/Views/OtherKamar/Setup.cshtml
@using Admin.Helper

<style>
    #modalsetup .input-detail td {
        white-space: nowrap;
    }
</style>

<div id="modalsetup" class="modal fade" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Kamar</h4>
            </div>
            <form autocomplete="off">
                <div class="modal-body">
                    <div class="form-horizontal">
                        <input type="hidden" name="_PROCESS" />
                        <input type="hidden" required name="Id" class="form-control" />

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="col-md-3 control-label">No Kamar</label>
                                    <div class="col-md-9">
                                        <input type="text" name="NoKamar"  class="form-control all-readonly" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-3 control-label">Nama Kamar</label>
                                    <div class="col-md-9">
                                        <input type="text" required name="NamaKamar" class="form-control" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-3 control-label">Sal</label>
                                    <div class="col-md-9">
                                        <select required name="Sal" class="form-control create-clear"></select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-3 control-label">JmlBed</label>
                                    <div class="col-md-9">
                                        <input type="number" required name="JmlBed" class="form-control" />
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="col-md-3 control-label">NoLantai</label>
                                    <div class="col-md-9">
                                        <input type="number" required name="NoLantai" class="form-control" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-3 control-label">&nbsp;</label>
                                    <div class="col-md-9">
                                        <label class="checkbox-inline">
                                            <input type="checkbox" name="Tambahan" />
                                            Tambahan
                                        </label>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-3 control-label">Kelas</label>
                                    <div class="col-md-9">
                                        <select required name="Kelas" class="form-control create-clear"></select>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12">
                                <div class="table-responsive">
                                    <table class="table table-bordered input-detail">
                                        <thead>
                                            <tr>
                                                <td style="width:50px;" class="text-center view-hide">
                                                    <a onclick="isetup.adddetailbody('')"><i class="icon icon-plus2"></i></a>
                                                </td>
                                                <td>No Bed</td>
                                            </tr>
                                        </thead>
                                        <tbody></tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn-save btn btn-primary"><i class="glyphicon glyphicon-floppy-disk"></i> SAVE</button>
                    <button type="submit" class="btn-delete btn btn-danger"><i class="glyphicon glyphicon-trash"></i> DELETE</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    var isetup;
    document.addEventListener("DOMContentLoaded", function (event) {
        isetup = new iSetup({
            modal: 'modalsetup',
            urldetail: '@Url.Action("Detail")',
            urlsave: '@Url.Action("Save")',
            detailsuccess: function (r, proc) {
                r = JSON.parse(r);
                if (r.IsSuccess) {
                    var t = isetup.form;

                    // value
                    t['Id'].value = r.Data.Id;
                    t['NoKamar'].value = r.Data.NoKamar;
                    t['NamaKamar'].value = r.Data.NamaKamar;
                    t['Sal'].value = r.Data.SalName;
                    t['JmlBed'].value = r.Data.JmlBed;
                    t['NoLantai'].value = r.Data.NoLantai;
                    t['Tambahan'].checked = r.Data.Tambahan;
                    t['Kelas'].value = r.Data.Kelas;

                    if (r.Data.SalName) {
                        const option = new Option(`${r.Data.SalName}`, r.Data.SalID, true, true);
                        $(t['Sal']).append(option);
                    }
                    if (r.Data.Kelas) {
                        const option = new Option(`${r.Data.KelasName}`, r.Data.Kelas, true, true);
                        $(t['Kelas']).append(option);
                    }

                    // detail
                    $(t).find('.input-detail tbody').html('');
                    $.each(r.Detail, function (index, value) {
                        isetup.adddetailbody(
                            value.Id
                        );
                    });

                    isetup.init();

                    if (isetup.form['_PROCESS'].value === 'EDIT') {
                        $(isetup.form['Id']).attr('readonly', 'readonly');
                    }

                    isetup.modal.modal({backdrop: 'static'});
                } else
                    alerterror(r.Message);
            },
            saveparam: function () {
                var t = isetup.form;
                return {
                    _process: t['_PROCESS'].value,
                    model: {

                        // param
                        NoKamar: t['NoKamar'].value,
                        NamaKamar: t['NamaKamar'].value,
                        Sal: t['Sal'].value,
                        JmlBed: t['JmlBed'].value,
                        NoLantai: t['NoLantai'].value,
                        Tambahan: t['Tambahan'].checked,
                        Kelas: t['Kelas'].value,
                        Detail: $.map($(t).find('.input-detail tbody tr'), function (value) {
                            return {
                                Id: $(value).find('.Id').val()
                            }
                        })
                    }
                }
            },
            savesuccess: function (r) {
                r = JSON.parse(r);
                if (r.IsSuccess) {
                    isetup.modal.modal('hide');
                    itable.refresh();
                } else alerterror(r.Message);
            },
            setupready: function () {
                var t = isetup.form;
                if (t['_PROCESS'].value === 'DELETE') $(t).find('[type="submit"].btn-danger').focus();
            },
            onopenmodalcreate: function (t, param) {
                isetup.init();
                $(isetup.form).find('.input-detail tbody').html('');
            }
        });

        $(isetup.form['Sal']).select2({
            ajax: {
                url: "@Url.Action("Other_Kamar_Sal", "Select2")",
                dataType: 'json',type: "POST",delay: 250,
                data: function (params) {return {pagesize: 30,pageindex: params.page || 0,filter: params.term};},
                processResults: function (data, params) {
                    if (!data.IsSuccess) alertpopup(data.Message, 'danger');
                    else {
                        params.page = data.PageIndex + 1;
                        return {
                            results: $.map(data.Data, function (value, index) {
                                return {
                                    id: value.Id,
                                    text: value.Nama,
                                }
                            }), pagination: { more: (params.page * 30) < data.TotalCount }
                        };
                    }
                }, cache: true
            },
            allowClear: true,
            placeholder: ""
        });

        $(isetup.form['Kelas']).select2({
            ajax: {
                url: "@Url.Action("Other_Kamar_Kelas", "Select2")",
                dataType: 'json',type: "POST",delay: 250,
                data: function (params) {return {pagesize: 30,pageindex: params.page || 0,filter: params.term};},
                processResults: function (data, params) {
                    if (!data.IsSuccess) alertpopup(data.Message, 'danger');
                    else {
                        params.page = data.PageIndex + 1;
                        return {
                            results: $.map(data.Data, function (value, index) {
                                return {
                                    id: value.Id,
                                    text: value.Nama,
                                }
                            }), pagination: { more: (params.page * 30) < data.TotalCount }
                        };
                    }
                }, cache: true
            },
            allowClear: true,
            placeholder: ""
        });

        isetup.adddetailbody = (id) => {
            var _detail = '';
            _detail += '<tr>';
            _detail += '<td class="text-center view-hide">';
            _detail += '<a href="#" onclick="removedetail(this);" class="text-danger"><i class="icon-trash"></i></a>';
            _detail += '</td>';

            // input
            _detail += '<td><input type="text" class="form-control Id" value="' + id + '" /></td>';

            _detail += '</tr>';
            $(isetup.form).find('tbody').append(_detail);
        };
    });
</script>